#**************************************************************************
#filebeat.yml
#**************************************************************************

filebeat.inputs:
    - type: log
      enabled: true
      paths:
        - /data/logstash-tutorial.log

output.logstash:
  enabled: true
  hosts: ["40.84.129.164:9704"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
